#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: e9ee2b3f-ae6a-478c-b6af-99966efe0a61
# Source File: MainForm.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
qQMAAB+LCAAAAAAABABlk0ePo1gAhO9I/IfWXJGGjEHqaYlowOBAxjfA5AfYDxN//fb0XlbaOpWq
VKfS9+nk2TDncFOSd/LxbcZ66P/8on8Tv75Q5OPj8wLrsu4ToNUgPydd/mUnda8NsPv9HItP/H/1
z+hv/3W7qkcSA3MgLqIoYZYs/itJVAAAwkw1or8++P7gveM85sT2Ks9lWzbh5hPcCUrTWJzkKIcV
ZTcrCaqeZmgUkZM2BnbggANru5J61AWh6QWMtGfGxwfJMPFDemZcu150B9tIG158jHBkem5OKxgE
kyNfr0lvEtbqcBRJdUM/dZrrWWto4nNsqjXrVYEtnZzEDzmP2r3Wug4GxkZZadZquehvJ6UwmzYE
Tlx1rVKJdYRFZlEiiiRZQNmsNmwQaENZHMllIINa1oKn0Qcdc/ce/Gu6hUBYinUiPevu39j5mK21
vdy8iU5XXdcPkfkC0a1CEZJSWJKsn351XqTWmCmX93P1qptvboi2jluSAvQUtfswl/s05W+tPdXN
gXfUTF+D3RW8S3CA12LFSB5F7nUHlR5LkprUGPyoh+3ff+jvfyBLZStwlCh802vPHQ07morxLjOa
78SEKjnSg8kMoIxLZ2E1428jisTxY+nsZeJHildltVAcp1DLqp3t8FGty4aFhZgNL/PAJrhfd7EV
6Xr79Lbng927szmoRDmRYSTYAWagyHVJyYdh0VhRqlC/S6ABfbYOcrouew/Ce50stNxLL+aeFprX
2tX44JdXtttjupOncn32xJUT3Ea4bi6KzKr3bJMjNFv53RAUxQFvOpa5zmSsMkWzI+RuslqCWDLL
Ht/Yu5jtUmzTMD270PEhrW8eVQ8UNph1iCLlxSMnuKYzD6yWT02heJEXYVkPs+LuER7Ss1ZRm/Dk
w4OiR4eWuJfBk7noDOyVELrZTHiC+tid4bolKIJZvJSQTGIGN/sbhT+f+A8qP9CI45h3Kajz8QP/
Tj7x/6L59Q8tzCw/qQMAAA==#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.149
     Generated on:       06.05.2020 12:07
     Generated by:       SUPER MARCIN
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-MainForm_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formCitrixInstall = New-Object 'System.Windows.Forms.Form'
	$btncheck = New-Object 'System.Windows.Forms.Button'
	$labelInformation = New-Object 'System.Windows.Forms.Label'
	$infobox = New-Object 'System.Windows.Forms.TextBox'
	$labelMachines = New-Object 'System.Windows.Forms.Label'
	$machinesbox = New-Object 'System.Windows.Forms.TextBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formCitrixInstall_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$btncheck_Click={
		#TODO: Place custom script here
		$machines = $machinesbox.Lines
		$btncheck.Enabled = $false
		foreach ($machine in $machines)
		{
			$test = Test-Connection $machine -Quiet -Count 1
			if ($test)
			{
				$regVal = "{1D8E6291-B0D5-35EC-8441-6616F567A0F7}"
				$data = Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$regVal -Name InstallDate | select InstallDate
				$data2 = $data.Installdate
				if ($data2)
				{
				$infobox.Text += "Install date on $machine is $data2 `r`n";
				}
				else
				{
					$infobox.Text += "No citrix installed `r`n";
				}
			}
			else
			{
				$infobox.Text += "Machine $machine is OFFLINE!`r`n";
			}
		}
		$btncheck.Enabled = $true;
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formCitrixInstall.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$btncheck.remove_Click($btncheck_Click)
			$formCitrixInstall.remove_Load($formCitrixInstall_Load)
			$formCitrixInstall.remove_Load($Form_StateCorrection_Load)
			$formCitrixInstall.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formCitrixInstall.SuspendLayout()
	#
	# formCitrixInstall
	#
	$formCitrixInstall.Controls.Add($btncheck)
	$formCitrixInstall.Controls.Add($labelInformation)
	$formCitrixInstall.Controls.Add($infobox)
	$formCitrixInstall.Controls.Add($labelMachines)
	$formCitrixInstall.Controls.Add($machinesbox)
	$formCitrixInstall.AutoScaleDimensions = '6, 13'
	$formCitrixInstall.AutoScaleMode = 'Font'
	$formCitrixInstall.ClientSize = '481, 496'
	$formCitrixInstall.Name = 'formCitrixInstall'
	$formCitrixInstall.Text = 'Citrix Install'
	$formCitrixInstall.add_Load($formCitrixInstall_Load)
	#
	# btncheck
	#
	$btncheck.Location = '183, 440'
	$btncheck.Name = 'btncheck'
	$btncheck.Size = '286, 37'
	$btncheck.TabIndex = 4
	$btncheck.Text = 'Check now'
	$btncheck.UseCompatibleTextRendering = $True
	$btncheck.UseVisualStyleBackColor = $True
	$btncheck.add_Click($btncheck_Click)
	#
	# labelInformation
	#
	$labelInformation.AutoSize = $True
	$labelInformation.Location = '183, 19'
	$labelInformation.Name = 'labelInformation'
	$labelInformation.Size = '64, 17'
	$labelInformation.TabIndex = 3
	$labelInformation.Text = 'Information:'
	$labelInformation.UseCompatibleTextRendering = $True
	#
	# infobox
	#
	$infobox.Location = '183, 39'
	$infobox.Multiline = $True
	$infobox.Name = 'infobox'
	$infobox.Size = '286, 395'
	$infobox.TabIndex = 2
	#
	# labelMachines
	#
	$labelMachines.AutoSize = $True
	$labelMachines.Location = '12, 19'
	$labelMachines.Name = 'labelMachines'
	$labelMachines.Size = '56, 17'
	$labelMachines.TabIndex = 1
	$labelMachines.Text = 'Machines:'
	$labelMachines.UseCompatibleTextRendering = $True
	#
	# machinesbox
	#
	$machinesbox.Location = '12, 39'
	$machinesbox.Multiline = $True
	$machinesbox.Name = 'machinesbox'
	$machinesbox.Size = '100, 438'
	$machinesbox.TabIndex = 0
	$formCitrixInstall.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formCitrixInstall.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formCitrixInstall.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formCitrixInstall.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formCitrixInstall.ShowDialog()

} #End Function

#Call the form
Show-MainForm_psf | Out-Null
